version: '3'
services:
    postgres-db:
        image: mdillon/postgis:10-alpine
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=test
        volumes:
            - ./db-dump/:/docker-entrypoint-initdb.d
        ports:
            - '5555:5432'
        networks:
            - backend
    mysql-db:
        image: mysql:5.7.29
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=bibleengine
        ports:
            - '3306:3306'
networks:
    backend:
        external: true
