version: 2
workflows:
    version: 2
    build_test_deploy:
        jobs:
            - build_yarn
            - test:
                  requires:
                      - build_yarn
            - test_migrations:
                  requires:
                      - build_yarn
            - request_deploy_app:
                  type: approval
                  requires:
                    - test
                    - test_migrations
            - deploy_expo:
                  context: expo-credentials
                  requires:
                    - request_deploy_app
            - deploy_ios:
                  context: expo-credentials
                  requires:
                    - deploy_expo
            - deploy_android:
                  context: expo-credentials
                  requires:
                    - deploy_expo
jobs:
    build_yarn:
        docker:
            - image: circleci/node:13.5.0
        steps:
            - checkout
            - restore_cache:
                  name: Restore Yarn Package Cache
                  keys:
                      - yarn-pkg-{{ checksum "yarn.lock" }}
            - run: ls node_modules || yarn install --frozen-lockfile
            - run: ls app/node_modules || cd app && yarn install --frozen-lockfile
            - save_cache:
                  name: Save Yarn Package Cache
                  key: yarn-pkg-{{ checksum "yarn.lock" }}
                  paths:
                      - node_modules
                      - app/node_modules
    test:
        docker:
            - image: circleci/node:13.5.0
        steps:
            - checkout
            - restore_cache:
                  name: Restore Yarn Package Cache
                  keys:
                      - yarn-pkg-{{ checksum "yarn.lock" }}
            - run: yarn
            - run: cd core && yarn test
            - run: cd importers && yarn test
            - run: cd client && yarn test --passWithNoTests
            - run: cd app && yarn install
            - run: cd app && yarn test
    test_migrations:
        machine:
            image: ubuntu-1604:201903-01
        environment:
            BASH_ENV: /opt/circleci/.nvm/nvm.sh
        steps:
            - checkout
            - restore_cache:
                  name: Restore Yarn Package Cache
                  keys:
                      - yarn-pkg-{{ checksum "yarn.lock" }}
            - run: core/src/tests/install_yarn.sh
            - run: nvm use 13.5.0 && yarn
            - run: core/src/tests/mysql_migration_tests.sh
            - run: core/src/tests/postgres_migration_tests.sh
            - run: core/src/tests/sqlite_migration_tests.sh
    deploy_expo:
        docker:
            - image: circleci/node:13.5.0
        steps:
            - checkout
            - run: cd ~ && git clone https://github.com/danbenn/step-bible-secrets.git
            - run: cp ~/step-bible-secrets/.env app
            - restore_cache:
                  name: Restore Yarn Package Cache
                  keys:
                      - yarn-pkg-{{ checksum "yarn.lock" }}
            - run: cd app && yarn install --frozen-lockfile
            - run: cd app && yarn expo login --non-interactive -u technical@tyndalehouse.com
            - run: cd app && yarn expo publish --release-channel $(git rev-parse --short HEAD)
    deploy_android:
        docker:
            - image: circleci/node:13.5.0
        steps:
            - checkout
            - run: cd ~ && git clone https://github.com/danbenn/step-bible-secrets.git
            - run: cp ~/step-bible-secrets/android_upload_key_secrets.json ~/secrets.json
            - restore_cache:
                name: Restore Yarn Package Cache
                keys:
                    - yarn-pkg-{{ checksum "yarn.lock" }}
            - run: ls node_modules || yarn install --frozen-lockfile
            - run: cd app && yarn install --frozen-lockfile
            - run: cd app && yarn expo login --non-interactive -u technical@tyndalehouse.com
            - run: cd app && yarn expo upload:android --non-interactive --key ~/secrets.json
    deploy_ios:
        macos:
            xcode: 11.3.0
        steps:
            - checkout
            - restore_cache:
                  name: Restore Yarn Mac Package Cache
                  keys:
                      - yarn-mac-{{ checksum "yarn.lock" }}
            - run: ls node_modules || yarn install --frozen-lockfile
            - run: cd app && yarn install --frozen-lockfile
            - save_cache:
                  name: Save Yarn Mac Package Cache
                  key: yarn-mac-{{ checksum "yarn.lock" }}
                  paths:
                      - node_modules
                      - app/node_modules
            - run: cd app && yarn expo login --non-interactive -u technical@tyndalehouse.com
            - run: cd app && yarn expo upload:ios --non-interactive
