version: 2
workflows:
    version: 2
    build_test_deploy:
        jobs:
            - build_yarn
            - test:
                  requires:
                      - build_yarn
            - test_migrations:
                  requires:
                      - build_yarn
jobs:
    build_yarn:
        docker:
            - image: circleci/node:14.15.3
        steps:
            - checkout
            - restore_cache:
                  name: Restore Yarn Package Cache
                  keys:
                      - yarn-modules-{{ checksum "yarn.lock" }}
            - run: ls node_modules || yarn install --frozen-lockfile
            - save_cache:
                  name: Save Yarn Package Cache
                  key: yarn-modules-{{ checksum "yarn.lock" }}
                  paths:
                      - node_modules
    test:
        docker:
            - image: circleci/node:14.15.3
        steps:
            - checkout
            - restore_cache:
                  name: Restore Yarn Package Cache
                  keys:
                      - yarn-modules-{{ checksum "yarn.lock" }}
            - run: yarn install --frozen-lockfile
            - run: cd core && yarn test
            - run: cd importers && yarn test
            - run: cd client && yarn test --passWithNoTests
    test_migrations:
        machine:
            image: ubuntu-2004:202010-01
        environment:
            BASH_ENV: /opt/circleci/.nvm/nvm.sh
        steps:
            - checkout
            - run: core/src/tests/install_yarn.sh
            - restore_cache:
                  name: Restore Yarn Package Cache
                  keys:
                      - yarn-modules-{{ checksum "yarn.lock" }}
            - run: nvm use 14.15.3 && yarn install --frozen-lockfile
            - run: core/src/tests/sqlite_migration_tests.sh
            - run: core/src/tests/mysql_migration_tests.sh
            - run: core/src/tests/postgres_migration_tests.sh
